### ISSUE TITLE
detecting only alert(1) and confirm(1) 

### ISSUE THREAD

**Issue by bugbaba** [gwen001/testxss#2]
Hi Gwen,

I have just noticed that it is only detecting if payload alert(1) and confirm(1)

All the others aren't checked like `alert(0)`

It does effects in cases where `alert` is blocked or they have `alert(1)`  in blacklist as most of the public payloads have that 

In those cases `confirm` and `prompt` and even alert with non `1` might help 

I tried with 5 payloads

```
"><script>alert(0);</script>
"><script>alert(1337);</script>
"><script>alert('xss');</script>
"><script>alert(1);</script>
"><script>alert(2);</script>
```

And this is the result it got 

![ss1](https://user-images.githubusercontent.com/29960776/39958982-88804b98-5628-11e8-8e42-8747388bb7c5.png)

Regards,

**Comment by bugbaba** [comment]
On [Line no 3](https://github.com/gwen001/testxss/blob/8d86d52ad2d415e877d6b7b3da88d45d279e5feb/TestXss.php#L13) 

the `DEFAULT_INJECTION_ALERT ` constant variable is declared 

and the same is used to check in if condition at  [Line no 1123](https://github.com/gwen001/testxss/blob/8d86d52ad2d415e877d6b7b3da88d45d279e5feb/TestXss.php#L1123)


I couldn't understand yet how it is checking confirm function and just for update prompt function is not checked.

**Comment by gwen001** [comment]
Yes, I implemented that to avoid false positive, some website trigger an alert with a custom warning message when you visit it. I want to be sure that the alert is because of the XSS sript and not a stupid "Are you over 18?", you know...

To change that behavior you can update the line 1123:
`if( $m && $matches[2] == self::DEFAULT_INJECTION_ALERT ) {`
To the following:
`if( $m ) {`

**Comment by bugbaba** [comment]
Yups, your point does makes sense 
But i guess **only few porn sites does that** 

That change solved the issue of checking just `1`

But i am still not able to get how is `confirm` function getting checked in the code

Because payloads with `confirm` function is getting detected too. 

Could you point out that ? 


Thanks

**Comment by gwen001** [comment]
Check `phantom-xss.js` to see what JS functions are supported. Alert, Confirm and Prompt are.

Just commiting a patch because there was a typo there.

Thanks :)

**Comment by bugbaba** [comment]
Can confirm that it fixed the issue of prompt 

Thanks for being so responsive :+1:  :bowing_man: 

and keep posting blogs, It really helps and may be some day i will also get that one program to change my life :)
